name: saikou

on:
  push:
    branches: [kotlin_app] 
  pull_request:
    types: [opened, synchronize]
    
jobs:
  
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Kotlin Linter
        uses: vroy/gha-kotlin-linter@v3
